language: ruby
services:
  - docker
# only run CI-builds on main branch
branches:
  only:
  - main
rvm:
  - 2.7.0
addons:
  apt:
    update: true
before_install:
  - sudo apt-get -y install jq
  - gem install bundler -v 2.4.4
  - npm install
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false