# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lazy-load-image
  - jekyll-paginate-v2
  - jekyll-algolia

# Purgecss
# css_dir: "/assets/css"

# Lazyloader
lazy_load_image:
  src_attr_name: data-src
  class_attr_values:
    - lazyload

# jekyll-seo-tag configuration
author: ""
baseurl: ""
url: "https://stargate.io"
title: "Stargate"
description: "An open source API framework for data."
discord: ""
github_username: "stargate"
twitter:
  username: "stargateio"
  card: "large"
logo: "/assets/images/astranaut.png"
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/images/default-stargate.png"

# Site Settings
facebook_id: "321313032622303"
github_repository: "stargate/stargate"
github_stars: 238
github_forks: 772
github_watchers: 3687

# autopages Settings
autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    layouts:
      - tags.html
    permalink: '/tag/:tag'
    enabled: true
    slugify:
      mode: 'default'
      case: true

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Algolia Settings
algolia:
  key: "70b4b7b67f5eb49a8a0950f64773f4d4" # Algolia Public Key (Search key)
  application_id: "CVUVTRE4BD"
  index_name: "Stargate"
  docs_index: "docs"

# Keep files in _site directory on builds
keep_files:
  - .git
  - docs
  - CNAME

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - script
  - config.json
  
